# Generated by Django 6.0.5 on 2026-05-28 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DfeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nfce_sc_cert_cnpj_contador', models.CharField(help_text='CNPJ do escritório contábil responsável pelo certificado.', max_length=14)),
                ('cert_path', models.CharField(max_length=500)),
                ('cert_password', models.CharField(max_length=255)),
                ('ver_aplic', models.CharField(default='NFCE-DJANGO-1.0', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DfeSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_nsu_sc', models.BigIntegerField(default=0)),
                ('ultima_captura', models.DateTimeField(blank=True, null=True)),
                ('proxima_captura_em', models.DateTimeField(blank=True, null=True)),
                ('bloqueado_ate', models.DateTimeField(blank=True, null=True)),
                ('ultimo_cstat', models.CharField(blank=True, max_length=10, null=True)),
                ('ultimo_motivo', models.TextField(blank=True, null=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dfe.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='NfceDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_acesso', models.CharField(db_index=True, max_length=44)),
                ('nsu', models.BigIntegerField(db_index=True)),
                ('tipo_documento', models.CharField(choices=[('NFE_PROC', 'NFC-e'), ('EVENTO_CANCELAMENTO', 'Evento de Cancelamento'), ('OUTRO_EVENTO', 'Outro Evento')], max_length=30)),
                ('xml', models.TextField()),
                ('cancelada', models.BooleanField(default=False)),
                ('capturado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dfe.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'chave_acesso', 'nsu')},
            },
        ),
    ]
