# Generated by Django 6.0.5 on 2026-05-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfcedocumento',
            name='cancelamento_verificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
