# Generated by Django 6.0.5 on 2026-05-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfe', '0002_nfcedocumento_cancelamento_verificado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfesyncstate',
            name='resync_ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dfesyncstate',
            name='resync_nsu_inicial',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dfesyncstate',
            name='ultimo_resync_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
