# Generated by Django 6.0.5 on 2026-05-28 16:55

import dfe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfe', '0003_dfesyncstate_resync_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cert_cnpj_titular',
            field=models.CharField(blank=True, default='', help_text='CNPJ extraído do certificado no momento do upload.', max_length=14),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cert_password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cert_pfx',
            field=models.FileField(blank=True, help_text='Certificado digital A1 (.pfx) da própria empresa (e-CNPJ).', null=True, upload_to=dfe.models.empresa_cert_upload_path),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cert_validade',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ver_aplic',
            field=models.CharField(default='NFCE-DJANGO-1.0', max_length=20),
        ),
    ]
