# Generated by Django 6.0.5 on 2026-05-28 17:00

import dfe.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfe', '0004_empresa_cert_cnpj_titular_empresa_cert_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='cert_password',
        ),
        migrations.AddField(
            model_name='empresa',
            name='cert_password_encrypted',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cert_pfx',
            field=models.FileField(blank=True, help_text='Certificado digital A1 (.pfx) da própria empresa (e-CNPJ). Armazenado em diretório privado, não exposto via HTTP.', null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\ti02\\nfce\\private_certs'), upload_to=dfe.models.empresa_cert_upload_path),
        ),
    ]
