# Generated by Django 6.0.5 on 2026-05-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfe', '0007_backfill_canceladas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfcedocumento',
            name='xml',
        ),
        migrations.AddField(
            model_name='nfcedocumento',
            name='arquivo_entrada',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='nfcedocumento',
            name='arquivo_zip',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
