# Generated by Django 6.0.5 on 2026-05-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfe', '0008_remove_nfcedocumento_xml_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfcedocumento',
            name='numero_nfce',
            field=models.CharField(blank=True, db_index=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='nfcedocumento',
            name='serie',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='nfcedocumento',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
