# Generated by Django 6.0.5 on 2026-05-29 11:28

import dfe.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfe', '0009_nfcedocumento_numero_nfce_nfcedocumento_serie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfesetting',
            name='cert_password_encrypted',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dfesetting',
            name='cert_pfx',
            field=models.FileField(blank=True, help_text='Certificado A1 (.pfx) do contador. Usado por todas as empresas sem certificado próprio. Armazenado em diretório privado.', null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\ti02\\nfce\\private_certs'), upload_to=dfe.models.contador_cert_upload_path),
        ),
        migrations.AddField(
            model_name='dfesetting',
            name='cert_validade',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dfesetting',
            name='cert_password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='dfesetting',
            name='cert_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='dfesetting',
            name='nfce_sc_cert_cnpj_contador',
            field=models.CharField(blank=True, default='', help_text='CNPJ do escritório contábil (lido do certificado no upload).', max_length=14),
        ),
    ]
