# Generated by Django 6.0.5 on 2026-05-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfe', '0010_dfesetting_cert_password_encrypted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfesyncstate',
            name='ultimo_erro',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dfesyncstate',
            name='ultimo_erro_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
