# Generated by Django 6.0.5 on 2026-05-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfe', '0011_dfesyncstate_ultimo_erro_dfesyncstate_ultimo_erro_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfesyncstate',
            name='em_execucao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dfesyncstate',
            name='execucao_iniciada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dfesyncstate',
            name='worker_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
