# Generated by Django 6.0.5 on 2026-05-29 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfe', '0012_dfesyncstate_em_execucao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapturaHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('nsu_inicial', models.BigIntegerField(default=0)),
                ('nsu_final', models.BigIntegerField(default=0)),
                ('qt_vigentes', models.IntegerField(default=0)),
                ('qt_canceladas', models.IntegerField(default=0)),
                ('cstat', models.CharField(blank=True, max_length=10, null=True)),
                ('xmotivo', models.TextField(blank=True, null=True)),
                ('erro', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dfe.empresa')),
            ],
            options={
                'ordering': ['-inicio'],
            },
        ),
    ]
