# Generated by Codex on 2026-06-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfe', '0013_capturahistorico'),
    ]

    operations = [
        migrations.CreateModel(
            name='SefazScChamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(db_index=True, max_length=14)),
                ('certificado', models.CharField(blank=True, default='', max_length=255)),
                ('ambiente', models.CharField(default='producao', max_length=20)),
                ('tipo_execucao', models.CharField(blank=True, default='', max_length=30)),
                ('filtro', models.CharField(blank=True, default='', max_length=80)),
                ('ult_nsu_enviado', models.BigIntegerField(blank=True, null=True)),
                ('cstat', models.CharField(blank=True, default='', max_length=10)),
                ('xmotivo', models.TextField(blank=True, default='')),
                ('ult_nsu_ret', models.BigIntegerField(blank=True, null=True)),
                ('qt_dfe_ret', models.IntegerField(blank=True, null=True)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('tempo_resposta_ms', models.IntegerField(blank=True, null=True)),
                ('erro_tecnico', models.TextField(blank=True, default='')),
                ('request_path', models.CharField(blank=True, default='', max_length=500)),
                ('response_path', models.CharField(blank=True, default='', max_length=500)),
                ('tentativa', models.IntegerField(default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [
                    models.Index(fields=['cnpj', '-criado_em'], name='dfe_sefazsc_cnpj_5d92a8_idx'),
                    models.Index(fields=['cstat', '-criado_em'], name='dfe_sefazsc_cstat_75a748_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='DfeExecucaoLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14)),
                ('tipo_execucao', models.CharField(max_length=30)),
                ('certificado', models.CharField(max_length=255)),
                ('filtro', models.CharField(blank=True, default='', max_length=80)),
                ('worker_id', models.CharField(blank=True, default='', max_length=120)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField(db_index=True)),
            ],
            options={
                'indexes': [
                    models.Index(fields=['cnpj', 'tipo_execucao'], name='dfe_dfeexec_cnpj_6862e1_idx'),
                    models.Index(fields=['expira_em'], name='dfe_dfeexec_expira__f3bb54_idx'),
                ],
                'unique_together': {('cnpj', 'tipo_execucao', 'certificado', 'filtro')},
            },
        ),
    ]
